-- Migration: create required tables for StudyWell
-- Run this SQL in your Supabase SQL editor or psql connected to the Supabase DB

-- Users table
CREATE TABLE IF NOT EXISTS public.users (
  email text PRIMARY KEY,
  username text,
  password text,
  institution text,
  role text DEFAULT 'Student',
  subscription jsonb,
  avatarId text,
  profilePicture text,
  created_at timestamptz DEFAULT now()
);

-- Payments table
CREATE TABLE IF NOT EXISTS public.payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id text,
  user_email text REFERENCES public.users(email) ON DELETE SET NULL,
  amount text,
  currency text,
  capture_response jsonb,
  created_at timestamptz DEFAULT now()
);

-- Email confirmations table
CREATE TABLE IF NOT EXISTS public.email_confirmations (
  token text PRIMARY KEY,
  email text,
  username text,
  password_hash text,
  institution text,
  expires_at timestamptz
);

-- Audit logs table
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id bigserial PRIMARY KEY,
  timestamp timestamptz NOT NULL DEFAULT now(),
  actor text,
  action text NOT NULL,
  details jsonb
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp ON public.audit_logs (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_payments_user_email ON public.payments (user_email);

-- Grants: if using Supabase service_role key for server, privileges are handled there; adjust as needed for policies.

-- End of migration
