- name: Vercel Actions
  uses: nexterias/actions-vercel@v1.2.3
  with:
    token: ${{ secrets.VERCEL_TOKEN }}         # Vercel token: https://vercel.com/account/tokens
    project-id: ${{ secrets.VERCEL_PROJECT_ID }}   # Vercel project ID
    org-id: ${{ secrets.VERCEL_ORG_ID }}           # User ID within Vercel
    # github-token: ${{ secrets.GITHUB_TOKEN }}    # optional, usually default is fine
    # production: true                            # optional
    # prebuilt: false                             # optional
    # cwd: .                                      # optional
    # domain-alias: example.com                   # optional
    # github-deployment-environment: production   # optional
    # public: false                               # optional
    # build-env:                                  # optional
    # env:                                        # optional
